// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/blog" | "/admin/blog/edit/[id]" | "/admin/blog/editor" | "/admin/blog/new" | "/admin/demo-requests" | "/admin/donations" | "/admin/in-app-messages" | "/admin/new" | "/admin/projects" | "/admin/store" | "/admin/subscriptions" | "/admin/users" | "/dashboard" | "/dashboard/ai" | "/dashboard/analytics" | "/dashboard/app-development" | "/dashboard/automated-compliance-audits" | "/dashboard/backend-design" | "/dashboard/billing" | "/dashboard/blog/[slug]" | "/dashboard/business-consulting" | "/dashboard/cannabis-compliance" | "/dashboard/careers" | "/dashboard/cats" | "/dashboard/cheaper-prices" | "/dashboard/client-portal" | "/dashboard/cloud-based" | "/dashboard/cms" | "/dashboard/consulting" | "/dashboard/donations" | "/dashboard/ecommerce-sync" | "/dashboard/futuristic-design" | "/dashboard/hosting" | "/dashboard/integrated-pos-hardware" | "/dashboard/legal-aide" | "/dashboard/loyalty-and-crm" | "/dashboard/marketing" | "/dashboard/marketplace" | "/dashboard/membership" | "/dashboard/my-account" | "/dashboard/no-hidden-fees" | "/dashboard/notifications" | "/dashboard/opposition-research" | "/dashboard/pos-mobile-app" | "/dashboard/profile" | "/dashboard/publishing" | "/dashboard/real-time-reports" | "/dashboard/reports" | "/dashboard/secure-cannabis-transactions" | "/dashboard/seo" | "/dashboard/startup-marketing" | "/dashboard/startup-support" | "/dashboard/states" | "/dashboard/subscriptions" | "/dashboard/support" | "/dashboard/team" | "/dashboard/ui-design" | "/dashboard/user-flexibility" | "/login"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/blog": {}
  "/admin/blog/edit/[id]": { "id": string; }
  "/admin/blog/editor": {}
  "/admin/blog/new": {}
  "/admin/demo-requests": {}
  "/admin/donations": {}
  "/admin/in-app-messages": {}
  "/admin/new": {}
  "/admin/projects": {}
  "/admin/store": {}
  "/admin/subscriptions": {}
  "/admin/users": {}
  "/dashboard": {}
  "/dashboard/ai": {}
  "/dashboard/analytics": {}
  "/dashboard/app-development": {}
  "/dashboard/automated-compliance-audits": {}
  "/dashboard/backend-design": {}
  "/dashboard/billing": {}
  "/dashboard/blog/[slug]": { "slug": string; }
  "/dashboard/business-consulting": {}
  "/dashboard/cannabis-compliance": {}
  "/dashboard/careers": {}
  "/dashboard/cats": {}
  "/dashboard/cheaper-prices": {}
  "/dashboard/client-portal": {}
  "/dashboard/cloud-based": {}
  "/dashboard/cms": {}
  "/dashboard/consulting": {}
  "/dashboard/donations": {}
  "/dashboard/ecommerce-sync": {}
  "/dashboard/futuristic-design": {}
  "/dashboard/hosting": {}
  "/dashboard/integrated-pos-hardware": {}
  "/dashboard/legal-aide": {}
  "/dashboard/loyalty-and-crm": {}
  "/dashboard/marketing": {}
  "/dashboard/marketplace": {}
  "/dashboard/membership": {}
  "/dashboard/my-account": {}
  "/dashboard/no-hidden-fees": {}
  "/dashboard/notifications": {}
  "/dashboard/opposition-research": {}
  "/dashboard/pos-mobile-app": {}
  "/dashboard/profile": {}
  "/dashboard/publishing": {}
  "/dashboard/real-time-reports": {}
  "/dashboard/reports": {}
  "/dashboard/secure-cannabis-transactions": {}
  "/dashboard/seo": {}
  "/dashboard/startup-marketing": {}
  "/dashboard/startup-support": {}
  "/dashboard/states": {}
  "/dashboard/subscriptions": {}
  "/dashboard/support": {}
  "/dashboard/team": {}
  "/dashboard/ui-design": {}
  "/dashboard/user-flexibility": {}
  "/login": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
