// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/admin/blog/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/edit/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/editor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/editor">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/editor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../src/app/admin/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/demo-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/demo-requests">> = Specific
  const handler = {} as typeof import("../../src/app/admin/demo-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/donations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/donations">> = Specific
  const handler = {} as typeof import("../../src/app/admin/donations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/in-app-messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/in-app-messages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/in-app-messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../src/app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/store">> = Specific
  const handler = {} as typeof import("../../src/app/admin/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ai">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/app-development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/app-development">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/app-development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/automated-compliance-audits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/automated-compliance-audits">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/automated-compliance-audits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/backend-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/backend-design">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/backend-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/business-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/business-consulting">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/business-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cannabis-compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cannabis-compliance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cannabis-compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/careers">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cats">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cheaper-prices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cheaper-prices">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cheaper-prices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/client-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/client-portal">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/client-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cloud-based/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cloud-based">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cloud-based/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cms">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/consulting">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/donations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/donations">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/donations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ecommerce-sync/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ecommerce-sync">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ecommerce-sync/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/futuristic-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/futuristic-design">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/futuristic-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/hosting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/hosting">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/hosting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/integrated-pos-hardware/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/integrated-pos-hardware">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/integrated-pos-hardware/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/legal-aide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/legal-aide">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/legal-aide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/loyalty-and-crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/loyalty-and-crm">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/loyalty-and-crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/membership/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membership">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/membership/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-account">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/no-hidden-fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/no-hidden-fees">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/no-hidden-fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/opposition-research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/opposition-research">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/opposition-research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/pos-mobile-app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pos-mobile-app">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/pos-mobile-app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/publishing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/publishing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/publishing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/real-time-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/real-time-reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/real-time-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/secure-cannabis-transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/secure-cannabis-transactions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/secure-cannabis-transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/seo">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/startup-marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/startup-marketing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/startup-marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/startup-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/startup-support">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/startup-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/states/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/states">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/states/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/team">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ui-design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ui-design">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ui-design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/user-flexibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user-flexibility">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/user-flexibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
